### ISSUE TITLE
$$XTIMAGE vs XTIMAGE and $$XSIMAGE vs XSIMAGE section

### ISSUE THREAD

**Issue by kaosengr** [PatrickvL/Dxbx#1]
Problem with XBEExplorer and display of XBE icons stored in XBE file.

I have a XBE file with the two sections named XTIMAGE and XSIMAGE and when viewing these icons in Resources the box is empty (solid white).

The listing of sections in the XBE shows both $$XTIMAGE and $$XSIMAGE but those are not the names I see for them in the actual XBE file. The section listing for XBEExplorer does seem to have proper size and location of the data in the file.  However, the two different areas, XBE Header and Resources, of XBEExplorer must use a different method to access/locate the data.

**Comment by PatrickvL** [comment]
Please attach a test case

**Comment by kaosengr** [comment]
Ok, the XBE file is part of OpenBOR v3.2 Build 3698 attached.

[OpenBOR v32 Build 3698.zip](https://github.com/PatrickvL/Dxbx/files/1868467/OpenBOR.v32.Build.3698.zip)

**Comment by PatrickvL** [comment]
Thank you, that's most helpful. Don't hesitate to inquire progress, as normally I'm very busy

**Comment by PatrickvL** [comment]
@kaosengr Could you explain your issue more detailed? I have a hard time understanding what your perceived problem is...

The OpenBOR xbe's you linked above show up just nicely in my most recent build; Let me do some finishing touches and upload a new build...

**Comment by PatrickvL** [comment]
![image](https://user-images.githubusercontent.com/461930/38251337-7ada61ea-3751-11e8-8742-ef084447be0f.png)

**Comment by PatrickvL** [comment]
@kaosengr Please try the latest build : https://github.com/PatrickvL/Dxbx/releases/tag/XbeExplorer

**Comment by kaosengr** [comment]
Okay, helps running the latest version.  I had a v1.0 version installed replaced it with the latest build and all is good.  

The sections in OpenBOR's XBE were named XTIMAGE and XSIMAGE guess it doesn't really matter the section name if their entry in the XBE header addresses the image data.

**Comment by kaosengr** [comment]
On second thought, I see the sections listed in XBEExplorer v1.2 (latest version) shown as $$XTIMAGE and $$XSIMAGE however when I look at the section listing in another reverse-engineering framework radare2 it shows the names as XTIMAGE and XSIMAGE.  

Are the names in XBEExplorer hard-coded to show with the leading $$ characters?

**Comment by PatrickvL** [comment]
You're welcome!
